# Welcome to Minecraft Mondays!
# -----------------------------

# The URL which will accept or decline users.
url: https://example.com/api/games/bindings/guild/500612695570120704/game/minecraft/id/
kick: true
not_whitelisted_join: |
  CompSoc will soon switch the Minecraft server to whitelisted users only.
  To carry on without disruption, get you or your friend at RHUL to run
    !game minecraft add [mc username]
  in the CompSoc Discord server.
